# Generated by Django 2.2.12 on 2022-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.DecimalField(decimal_places=20, max_digits=50)),
                ('y', models.DecimalField(decimal_places=20, max_digits=50)),
                ('w', models.DecimalField(decimal_places=20, max_digits=50)),
                ('h', models.DecimalField(decimal_places=20, max_digits=50)),
                ('annotated_by', models.CharField(choices=[('p', 'PERSON'), ('m', 'MODEL')], default='p', max_length=5)),
                ('label_class', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
